### ISSUE TITLE
Video Resolution Unstable Issue.

### ISSUE THREAD

**Issue by mdsnalw** [aidenlx/media-extended#84] opened 2021-09-22 06:59 UTC
We are facing the video resolution unstable issue for resource from website Bilibili. Sometimes the resolution is clear with 1080P, while the majority of time is unclear with lower resolution ratio. 
Could it be possible to add the build in function to choose the resolution, such as enable the 1080P or 720P resolution to choose from? 
Or choose the best possible resolution which the stream media could provide? Thank you!

**Comment by aidenlx** [comment] 2021-09-22 07:41
duplicate of [mx-bili-plugin #5](https://github.com/aidenlx/mx-bili-plugin/issues/5)

**Closed by aidenlx** 2021-09-22 07:41 UTC
Labels: duplicate
