### ISSUE TITLE
"Watch on YouTube" link does not work, when YouTube embed is restricted

### ISSUE THREAD

**Issue by Elaws** [aidenlx/media-extended#118] opened 2022-02-15 23:40 UTC
Some videos do not allow embedding. Anyway, there is a link "Watch on YouTube" that should be clickable to access the content.

When clicking this link, nothing happens.

**Comment by aidenlx** [comment] 2022-02-16 03:18
duplicate of #83

**Closed by aidenlx** 2022-02-16 03:18 UTC
Labels: duplicate

**Comment by Elaws** [comment] 2022-02-16 17:44
Hello @aidenlx,

I'm not sure how this issue relates to #83 ? It does not seem related to me.

Here is what I meant :

When YouTube video is restricted, it will show as below :

![image](https://user-images.githubusercontent.com/52013479/154324346-f5203549-94eb-4663-a309-c8c972c683b4.png)

Here, if you click on "Watch on YouTube" (i.e. "Regarder sur YouTube"), nothing happens.

I hope this is clearer !

Thanks
